name: Generate errno maps

on: [push]

jobs:
  gen:

    runs-on: ${{ matrix.config.platform }}
    
    strategy:
      matrix:
        config:
          - name: darwin
            platform: macos-10.15
          - name: windows
            platform: windows-2019
          - name: linux
            platform: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: node gen.js > ${{ matrix.config.platform }}.js
      - name: Upload result artifact
        uses: actions/upload-artifact@v2
        with:
          name: errnomap_${{ matrix.config.name }}
          path: ${{ matrix.config.platform }}.js

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Retrieve linux output
      uses: actions/download-artifact@v2
      with:
        name: errnomap_linux
        path: test/linux
    - name: Retrieve darwin output
      uses: actions/download-artifact@v2
      with:
        name: errnomap_darwin
        path: test/darwin
    - name: Retrieve windows output
      uses: actions/download-artifact@v2
      with:
        name: errnomap_windows
        path: test/windows
    - name: Execute comparisons
      run: node test
